# Generated by Django 3.2 on 2021-05-21 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(default='', max_length=50)),
                ('PhoneNumber', models.CharField(default='', max_length=10)),
                ('Mail', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FilmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Type', models.CharField(default='', max_length=50)),
                ('Times', models.IntegerField(default=90)),
                ('Actor', models.CharField(default='', max_length=500)),
                ('Author', models.CharField(default='', max_length=50)),
                ('Premiere', models.DateField(default='')),
                ('Language', models.CharField(default='', max_length=100)),
                ('Rated', models.CharField(default='', max_length=100)),
                ('Photo', models.ImageField(null=True, upload_to='images/')),
                ('Background', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GuessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Sex', models.CharField(default='Khác', max_length=50)),
                ('DateOfBirth', models.DateField(default=datetime.date.today)),
                ('PhoneNumber', models.CharField(default='', max_length=10)),
                ('Mail', models.EmailField(default='', max_length=254)),
                ('Type', models.CharField(default='Normal', max_length=50)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Type', models.CharField(default='', max_length=50)),
                ('CinemaInfo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.cinemainfo')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfShow', models.DateField(default='')),
                ('Cost', models.CharField(default='', max_length=50)),
                ('End', models.TimeField(default='')),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.filmdata')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.room')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDef',
            fields=[
                ('Start', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chair', models.CharField(default='', max_length=30)),
                ('CinemaInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.cinemainfo')),
                ('GuessInfo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.guessinfo')),
                ('ShowTimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.showtimes')),
            ],
        ),
        migrations.AddField(
            model_name='showtimes',
            name='TimeDef_Start',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.timedef'),
        ),
        migrations.CreateModel(
            name='BillTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuessInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.guessinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FilmInCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CinemaInfo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.cinemainfo')),
                ('FilmData', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.filmdata')),
            ],
            options={
                'unique_together': {('FilmData', 'CinemaInfo')},
            },
        ),
        migrations.CreateModel(
            name='ChairInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=0)),
                ('Daytemp', models.DateField(default=datetime.date.today)),
                ('showtime', models.IntegerField(default=0)),
                ('Chair', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.chair')),
                ('Room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myWeb.room')),
            ],
            options={
                'unique_together': {('Room', 'Chair', 'showtime')},
            },
        ),
    ]
